[project]
requires-python=">=3.9"
name="manygit"


[project.optional_dependencies]
github = ["github3.py"]
gitlab = ["python-gitlab"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.black]
exclude = '^/(\.|dist|pybuild|venv)'

[tool.pyright]
typeCheckingMode = 'basic'
