name: Feature Tests

on: push

jobs:
  static-checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache-dependency-path: requirements
      - name: Run Commit Checks
        shell: bash
        run: |
          make dev-install
          pre-commit run --all

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache-dependency-path: requirements
      - name: Install
        shell: bash
        run: |
          make dev-install
      - name: Run Unit Tests
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITLAB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_GITLAB }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
        run: |
          make test
